### ISSUE TITLE
Segmentation fault: 11 on startup

### ISSUE THREAD

**Issue by Havnak** [EdvardSire/TTK4235-elevator#1]
"Segmentation fault: 11" when the elevator has reached the floor after initialization.:(

**Comment by EdvardSire** [comment]
Can you check if `cdf047ac091375cbd21404b053872a27cbabf0a3` does the same?

**Comment by Havnak** [comment]
With cdf047ac091375cbd21404b053872a27cbabf0a3:
Definied state established
Door closed
RequestToConsume
Segmentation fault: 11
